
services:
  proxy:
    image: nginx:alpine
    container_name: uber-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - ml_net
    depends_on:
      - app_blue
      - app_green

  app_blue:
    image: registry.gitflic.ru/project/golubspb5/ml-opc-taxi/app:${BLUE_TAG}
    container_name: uber-app-blue
    ports:
      - "5001:32000"
    environment:
      - APP_COLOR=blue
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:32000/"]
      interval: 10s
      timeout: 2s
      retries: 6
    networks:
      - ml_net

  app_green:
    image: registry.gitflic.ru/project/golubspb5/ml-opc-taxi/app:${GREEN_TAG}
    container_name: uber-app-green
    ports:
      - "5002:32000"
    environment:
      - APP_COLOR=green
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:32000/"]
      interval: 10s
      timeout: 2s
      retries: 6
    networks:
      - ml_net

networks:
  ml_net:
    driver: bridge